language: python
if: 'type = pull_request OR branch = master'
python:
  - "3.8"
install:
  - pip install --upgrade pip wheel setuptools
  - pip install Cython==0.29.21
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest==5.4.3
script:
  - pytest --doctest-modules
