language: python
if: 'type = pull_request OR branch = master'
python:
  - "3.8"
jobs:
  include:
    - os: osx
      language: sh
      python: "3.8"
      before_install:
        - brew update
        - python3.8 -m pip install virtualenv
        - virtualenv .venv -p python3.8
        - source .venv/bin/activate
    - os: windows
      language: sh
      python: "3.8"
      before_install:
        - choco install python3.8 --params "/InstallDir:C:\\Python"
        - export PATH="/c/Python:/c/Python/Scripts:$PATH"
install:
  - pip install --upgrade pip wheel setuptools
  - pip install Cython==0.29.21
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest==5.4.3
script:
  - pytest --doctest-modules
