language: python
if: 'type = pull_request OR branch = master'
python:
  - "3.8"
env:
  - SOFTWARE_DIR='.'
install:
  - pip install --upgrade pip wheel setuptools
  - pip install Cython==0.29.21 # pre-requisite
  - pip install git+https://github.com/giganticode/bohr-framework@v0.2.3
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pytest --doctest-modules
