stages:
  extract_train_data:
    cmd: 7z x downloaded-data/sample.7z -odata
    deps:
    - downloaded-data/sample.7z
    outs:
    - data/train:
        cache: false
  apply_heuristics_message:
    cmd: python bohr/pipeline/apply_heuristics.py bugginess --n-parallel=1 --commits-file data/train/bug_sample.csv --issues-file data/train/bug_sample_issues.csv --changes-file data/train/bug_sample_files.csv
    deps:
    - bohr/heuristics/keywords
    - bohr/heuristics/bugginess.py
    - bohr/pipeline/apply_heuristics.py
    - data/train
    - data/test
    outs:
    - generated/bugginess/heuristic_matrix_train.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_1151_commits.pkl
    - generated/bugginess/analysis_train.csv:
        cache: false
    - generated/bugginess/analysis_herzig.csv:
        cache: false
    - generated/bugginess/analysis_berger.csv:
        cache: false
    - generated/bugginess/analysis_1151_commits.csv:
        cache: false
    metrics:
    - metrics/bugginess/heuristic_metrics.json:
        cache: false
    - generated/bugginess/analysis_train.json:
        cache: false
    - generated/bugginess/analysis_herzig.json:
        cache: false
    - generated/bugginess/analysis_berger.json:
        cache: false
    - generated/bugginess/analysis_1151_commits.json:
        cache: false
  train_label_model_message:
    cmd: python bohr/pipeline/train_label_model.py bugginess
    deps:
    - bohr/pipeline/train_label_model.py
    - generated/bugginess/heuristic_matrix_train.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_1151_commits.pkl
    - data/train
    - data/test
    outs:
    - generated/bugginess/label_model.pkl
    metrics:
    - metrics/bugginess/label_model_metrics.json:
        cache: false
  label_dataset_message_issues:
    cmd: python bohr/pipeline/label_dataset.py bugginess --commits-file data/train/bug_sample.csv -o labeled_with_model2.csv --debug
    deps:
      - bohr/pipeline/label_dataset.py
      - generated/bugginess/heuristic_matrix_train.pkl
      - data/train
    outs:
      - labeled_with_model2.csv
