stages:
  parse_labels:
    cmd: python bohr/pipeline/parse_labels.py
    deps:
    - bohr/pipeline/labels
    - bohr/pipeline/parse_labels.py
    - bohr/resources/labels.template
    - bohr/labels
    outs:
    - bohr/labels.py:
        cache: false
  extract_train_data:
    cmd: 7z x downloaded-data/sample.7z -odata
    deps:
    - downloaded-data/sample.7z
    outs:
    - data/train:
        cache: false
  apply_heuristics_bugginess:
    cmd: python bohr/pipeline/apply_heuristics.py bugginess
    deps:
    - bohr/pipeline/apply_heuristics.py
    - bohr/labels.py
    - bohr/core.py
    - bohr/heuristics
    - bohr/artifacts
    - data/test
    - data/train
    - bohr/tasks/bugginess.py
    outs:
    - generated/bugginess/heuristic_matrix_train.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/analysis_train.csv:
        cache: false
    - generated/bugginess/analysis_herzig.csv:
        cache: false
    - generated/bugginess/analysis_berger.csv:
        cache: false
    - generated/bugginess/analysis_1151-commits.csv:
        cache: false
    metrics:
    - metrics/bugginess/heuristic_metrics.json:
        cache: false
    - metrics/bugginess/analysis_train.json:
        cache: false
    - metrics/bugginess/analysis_herzig.json:
        cache: false
    - metrics/bugginess/analysis_berger.json:
        cache: false
    - metrics/bugginess/analysis_1151-commits.json:
        cache: false
  train_label_model_bugginess:
    cmd: python bohr/pipeline/train_label_model.py bugginess
    deps:
    - bohr/pipeline/train_label_model.py
    - generated/bugginess/heuristic_matrix_train.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - data/train
    - data/test
    outs:
    - generated/bugginess/label_model.pkl
    metrics:
    - metrics/bugginess/label_model_metrics.json:
        cache: false
  label_dataset_bugginess:
    cmd: python bohr/pipeline/label_dataset.py bugginess bugginess-train
    deps:
    - bohr/pipeline/label_dataset.py
    - generated/bugginess/heuristic_matrix_train.pkl
    - data/train
    outs:
    - labeled-data/bugginess-train.csv
  apply_heuristics_bugginess_10k:
    cmd: python bohr/pipeline/apply_heuristics.py bugginess-10k
    deps:
      - bohr/pipeline/apply_heuristics.py
      - bohr/labels.py
      - bohr/core.py
      - bohr/heuristics
      - bohr/artifacts
      - data/test
      - data/train
      - bohr/tasks/bugginess-10k.py
    outs:
      - generated/bugginess-10k/heuristic_matrix_train.pkl
      - generated/bugginess-10k/heuristic_matrix_herzig.pkl
      - generated/bugginess-10k/heuristic_matrix_berger.pkl
      - generated/bugginess-10k/heuristic_matrix_1151-commits.pkl
      - generated/bugginess-10k/analysis_train.csv:
          cache: false
      - generated/bugginess-10k/analysis_herzig.csv:
          cache: false
      - generated/bugginess-10k/analysis_berger.csv:
          cache: false
      - generated/bugginess-10k/analysis_1151-commits.csv:
          cache: false
    metrics:
      - metrics/bugginess-10k/heuristic_metrics.json:
          cache: false
      - metrics/bugginess-10k/analysis_train.json:
          cache: false
      - metrics/bugginess-10k/analysis_herzig.json:
          cache: false
      - metrics/bugginess-10k/analysis_berger.json:
          cache: false
      - metrics/bugginess-10k/analysis_1151-commits.json:
          cache: false
  train_label_model_bugginess_10k:
    cmd: python bohr/pipeline/train_label_model.py bugginess-10k
    deps:
      - bohr/pipeline/train_label_model.py
      - generated/bugginess-10k/heuristic_matrix_train.pkl
      - generated/bugginess-10k/heuristic_matrix_herzig.pkl
      - generated/bugginess-10k/heuristic_matrix_berger.pkl
      - generated/bugginess-10k/heuristic_matrix_1151-commits.pkl
      - data/train
      - data/test
    outs:
      - generated/bugginess-10k/label_model.pkl
    metrics:
      - metrics/bugginess-10k/label_model_metrics.json:
          cache: false
  label_dataset_bugginess_10k:
    cmd: python bohr/pipeline/label_dataset.py bugginess-10k bugginess-train-10k
    deps:
      - bohr/pipeline/label_dataset.py
      - generated/bugginess-10k/heuristic_matrix_train.pkl
      - data/train
    outs:
      - labeled-data/bugginess-train-10k.csv
  preprocess-and-split-smell-dataset:
    cmd: data-preprocessing/smells.sh
    deps:
      - data-preprocessing/smells.sh
      - downloaded-data/smells-madeyski.csv
    outs:
      - data/smells/test.csv
      - data/smells/train.csv
  apply_heuristics_smells:
    cmd: python bohr/pipeline/apply_heuristics.py smells
    deps:
      - bohr/pipeline/apply_heuristics.py
      - bohr/labels.py
      - bohr/core.py
      - bohr/heuristics
      - bohr/artifacts
      - data/smells
      - bohr/tasks/smells.py
      - bohr/datasets
    outs:
      - generated/smells/heuristic_matrix_train.pkl
      - generated/smells/heuristic_matrix_smells-test.pkl
      - generated/smells/analysis_train.csv:
          cache: false
      - generated/smells/analysis_smells-test.csv:
          cache: false
    metrics:
      - metrics/smells/heuristic_metrics.json:
          cache: false
      - metrics/smells/analysis_train.json:
          cache: false
      - metrics/smells/analysis_smells-test.json:
          cache: false
  train_label_model_smells:
    cmd: python bohr/pipeline/train_label_model.py smells
    deps:
      - bohr/pipeline/train_label_model.py
      - generated/smells/heuristic_matrix_train.pkl
      - generated/smells/heuristic_matrix_smells-test.pkl
      - bohr/tasks/smells.py
      - data/smells
      - bohr/datasets
    outs:
      - generated/smells/label_model.pkl
    metrics:
      - metrics/smells/label_model_metrics.json:
          cache: false
  label_dataset_bugginess_smells:
    cmd: python bohr/pipeline/label_dataset.py smells smells-train
    deps:
      - bohr/pipeline/label_dataset.py
      - generated/smells/heuristic_matrix_train.pkl
      - data/smells/train.csv
      - bohr/tasks/smells.py
      - bohr/datasets
    outs:
      - labeled-data/smells-train.csv
  apply_heuristics_smells_10:
    cmd: python bohr/pipeline/apply_heuristics.py smells_10
    deps:
      - bohr/pipeline/apply_heuristics.py
      - bohr/labels.py
      - bohr/core.py
      - bohr/heuristics
      - bohr/artifacts
      - data/smells
      - bohr/tasks/smells-test_10.py
      - bohr/datasets
    outs:
      - generated/smells_10/heuristic_matrix_train.pkl
      - generated/smells_10/heuristic_matrix_smells-test.pkl
      - generated/smells_10/analysis_train.csv:
          cache: false
      - generated/smells_10/analysis_smells-test.csv:
          cache: false
    metrics:
      - metrics/smells_10/heuristic_metrics.json:
          cache: false
      - metrics/smells_10/analysis_train.json:
          cache: false
      - metrics/smells_10/analysis_smells-test.json:
          cache: false
  train_label_smells_10:
    cmd: python bohr/pipeline/train_label_model.py smells_10
    deps:
      - bohr/pipeline/train_label_model.py
      - generated/smells_10/heuristic_matrix_train.pkl
      - generated/smells_10/heuristic_matrix_smells-test.pkl
      - bohr/tasks/smells-test_10.py
      - data/smells
      - bohr/datasets
    outs:
      - generated/smells_10/label_model.pkl
    metrics:
      - metrics/smells_10/label_model_metrics.json:
          cache: false
  label_dataset_smells_10:
    cmd: python bohr/pipeline/label_dataset.py smells_10 smells-train_10
    deps:
      - bohr/pipeline/label_dataset.py
      - generated/smells_10/heuristic_matrix_train.pkl
      - data/smells_10/train.csv
      - bohr/tasks/smells-test_10.py
      - bohr/datasets
    outs:
      - labeled-data/smells-train_10.csv
