stages:
  preprocess_berger:
    cmd: cp downloaded-data/berger.csv data && echo "data/berger.csv" >> .gitignore
      && git add .gitignore
    deps:
    - downloaded-data/berger.csv
    outs:
    - data/berger.csv:
        cache: false
  preprocess_herzig:
    cmd: cp downloaded-data/herzig.csv data && echo "data/herzig.csv" >> .gitignore
      && git add .gitignore
    deps:
    - downloaded-data/herzig.csv
    outs:
    - data/herzig.csv:
        cache: false
  preprocess_1151-commits:
    cmd: cp downloaded-data/1151-commits.csv data && echo "data/1151-commits.csv"
      >> .gitignore && git add .gitignore
    deps:
    - downloaded-data/1151-commits.csv
    outs:
    - data/1151-commits.csv:
        cache: false
  preprocess_bugginess-train:
    cmd: 7z x downloaded-data/bugginess_train.7z -odata/bugginess_train && echo "data/bugginess_train"
      >> .gitignore && git add .gitignore
    deps:
    - downloaded-data/bugginess_train.7z
    outs:
    - data/bugginess_train:
        cache: false
  preprocess_smells-train:
    cmd: data-preprocessing/smells.sh
    deps:
    - data-preprocessing/smells.sh
    - downloaded-data/smells-madeyski.csv
    outs:
    - data/smells/train.csv
  preprocess_smells-test:
    cmd: data-preprocessing/smells.sh
    deps:
    - data-preprocessing/smells.sh
    - downloaded-data/smells-madeyski.csv
    outs:
    - data/smells/test.csv
  parse_labels:
    cmd: bohr parse-labels
    deps:
    - labels
    outs:
    - labels.py:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__bugginess-train:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      bugginess-train
    deps:
    - data/bugginess_train
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_bugginess-train.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_bugginess-train.json:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__1151-commits:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      1151-commits
    deps:
    - data/1151-commits.csv
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_1151-commits.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_1151-commits.json:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__berger:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      berger
    deps:
    - data/berger.csv
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_berger.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_berger.json:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__herzig:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      herzig
    deps:
    - data/herzig.csv
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_herzig.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_herzig.json:
        cache: false
  bugginess_combine_heuristics:
    cmd: bohr apply-heuristics bugginess
    deps:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_bugginess-train.pkl
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_herzig.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/analysis_1151-commits.csv:
        cache: false
    - generated/bugginess/analysis_berger.csv:
        cache: false
    - generated/bugginess/analysis_bugginess-train.csv:
        cache: false
    - generated/bugginess/analysis_herzig.csv:
        cache: false
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_bugginess-train.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    metrics:
    - metrics/bugginess/analysis_1151-commits.json:
        cache: false
    - metrics/bugginess/analysis_berger.json:
        cache: false
    - metrics/bugginess/analysis_bugginess-train.json:
        cache: false
    - metrics/bugginess/analysis_herzig.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_1151-commits.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_berger.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_bugginess-train.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_herzig.json:
        cache: false
  bugginess_train_label_model:
    cmd: bohr train-label-model bugginess bugginess-train
    deps:
    - data/1151-commits.csv
    - data/berger.csv
    - data/herzig.csv
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_bugginess-train.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/label_model.pkl
    metrics:
    - metrics/bugginess/label_model_metrics.json:
        cache: false
  bugginess_label_dataset_bugginess-train:
    cmd: bohr label-dataset bugginess bugginess-train
    deps:
    - data/bugginess_train
    - generated/bugginess/heuristic_matrix_bugginess-train.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/bugginess-train.labeled.csv
  bugginess_label_dataset_1151-commits:
    cmd: bohr label-dataset bugginess 1151-commits
    deps:
    - data/1151-commits.csv
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/1151-commits.labeled.csv
  bugginess_label_dataset_berger:
    cmd: bohr label-dataset bugginess berger
    deps:
    - data/berger.csv
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/berger.labeled.csv
  bugginess_label_dataset_herzig:
    cmd: bohr label-dataset bugginess herzig
    deps:
    - data/herzig.csv
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/herzig.labeled.csv
  smells_apply_heuristics__heuristics_smells__smells-train:
    cmd: bohr apply-heuristics smells --heuristic-group heuristics.smells --dataset
      smells-train
    deps:
    - data/smells/train.csv
    - heuristics/keywords
    - heuristics/smells.py
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/smells/heuristics.smells/heuristic_matrix_smells-train.pkl
    metrics:
    - metrics/smells/heuristics.smells/heuristic_metrics_smells-train.json:
        cache: false
  smells_apply_heuristics__heuristics_smells__smells-test:
    cmd: bohr apply-heuristics smells --heuristic-group heuristics.smells --dataset
      smells-test
    deps:
    - data/smells/test.csv
    - heuristics/keywords
    - heuristics/smells.py
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/smells/heuristics.smells/heuristic_matrix_smells-test.pkl
    metrics:
    - metrics/smells/heuristics.smells/heuristic_metrics_smells-test.json:
        cache: false
  smells_combine_heuristics:
    cmd: bohr apply-heuristics smells
    deps:
    - generated/smells/heuristics.smells/heuristic_matrix_smells-test.pkl
    - generated/smells/heuristics.smells/heuristic_matrix_smells-train.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/smells/analysis_smells-test.csv:
        cache: false
    - generated/smells/analysis_smells-train.csv:
        cache: false
    - generated/smells/heuristic_matrix_smells-test.pkl
    - generated/smells/heuristic_matrix_smells-train.pkl
    metrics:
    - metrics/smells/analysis_smells-test.json:
        cache: false
    - metrics/smells/analysis_smells-train.json:
        cache: false
    - metrics/smells/heuristic_metrics_smells-test.json:
        cache: false
    - metrics/smells/heuristic_metrics_smells-train.json:
        cache: false
  smells_train_label_model:
    cmd: bohr train-label-model smells smells-train
    deps:
    - data/smells/test.csv
    - generated/smells/heuristic_matrix_smells-test.pkl
    - generated/smells/heuristic_matrix_smells-train.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/smells/label_model.pkl
    metrics:
    - metrics/smells/label_model_metrics.json:
        cache: false
  smells_label_dataset_smells-train:
    cmd: bohr label-dataset smells smells-train
    deps:
    - data/smells/train.csv
    - generated/smells/heuristic_matrix_smells-train.pkl
    - generated/smells/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/smells-train.labeled.csv
  smells_label_dataset_smells-test:
    cmd: bohr label-dataset smells smells-test
    deps:
    - data/smells/test.csv
    - generated/smells/heuristic_matrix_smells-test.pkl
    - generated/smells/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/smells-test.labeled.csv
  bugginess_transformer_train:
    cmd: bash classifiers/bugginess-transformer/train.sh labeled-data/bugginess.csv
    deps:
    - classifiers/bugginess-transformer/run.py
    - classifiers/bugginess-transformer/train.sh
    - labeled-datasets/bugginess-train.labeled.csv
    - requirements.txt
    outs:
    - models/config.json:
        cache: false
    - models/merges.txt:
        cache: false
    - models/pytorch_model.bin
    - models/special_tokens_map.json:
        cache: false
    - models/tokenizer_config.json:
        cache: false
    - models/training_args.bin
    - models/vocab.json:
        cache: false
  bugginess_transformer_test_herzig:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/herzig.csv
      metrics/bugginess/transformer/herzig
    deps:
    - classifiers/bugginess-transformer/run.py
    - classifiers/bugginess-transformer/test.sh
    - data/herzig.csv
    - models/config.json
    - models/merges.txt
    - models/pytorch_model.bin
    - models/special_tokens_map.json
    - models/tokenizer_config.json
    - models/training_args.bin
    - models/vocab.json
    - requirements.txt
    metrics:
    - metrics/bugginess/transformer/herzig/eval_results.txt:
        cache: false
  bugginess_combine_labels_1151-commits:
    cmd: python classifiers/bugginess-transformer/combine_labels.py labeled-datasets/1151-commits.labeled.csv
      metrics/bugginess/transformer/1151-commits/assigned_labels.csv labeled-datasets/1151-commits.labeled.both.csv
      && echo "labeled-datasets/1151-commits.labeled.both.csv" >> .gitignore
    deps:
    - classifiers/bugginess-transformer/combine_labels.py
    - labeled-datasets/1151-commits.labeled.csv
    - metrics/bugginess/transformer/1151-commits/assigned_labels.csv
    outs:
    - labeled-datasets/1151-commits.labeled.both.csv:
        cache: false
  bugginess_transformer_label_1151-commits:
    cmd: bash classifiers/bugginess-transformer/label.sh data/bugginess/1151-commits.csv
      metrics/bugginess/transformer/1151-commits
    deps:
    - classifiers/bugginess-transformer/label.sh
    - classifiers/bugginess-transformer/run.py
    - data/1151-commits.csv
    - models/config.json
    - models/merges.txt
    - models/pytorch_model.bin
    - models/special_tokens_map.json
    - models/tokenizer_config.json
    - models/training_args.bin
    - models/vocab.json
    - requirements.txt
    metrics:
    - metrics/bugginess/transformer/1151-commits/assigned_labels.csv:
        cache: false
  bugginess_transformer_test_berger:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/berger.csv
      metrics/bugginess/transformer/berger
    deps:
    - classifiers/bugginess-transformer/run.py
    - classifiers/bugginess-transformer/test.sh
    - data/berger.csv
    - models/config.json
    - models/merges.txt
    - models/pytorch_model.bin
    - models/special_tokens_map.json
    - models/tokenizer_config.json
    - models/training_args.bin
    - models/vocab.json
    - requirements.txt
    metrics:
    - metrics/bugginess/transformer/berger/eval_results.txt:
        cache: false
  bugginess_transformer_test_1151-commits:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/1151-commits.csv
      metrics/bugginess/transformer/1151-commits
    deps:
    - classifiers/bugginess-transformer/run.py
    - classifiers/bugginess-transformer/test.sh
    - data/1151-commits.csv
    - models/config.json
    - models/merges.txt
    - models/pytorch_model.bin
    - models/special_tokens_map.json
    - models/tokenizer_config.json
    - models/training_args.bin
    - models/vocab.json
    - requirements.txt
    metrics:
    - metrics/bugginess/transformer/1151-commits/eval_results.txt:
        cache: false
