stages:
  parse_labels:
    cmd: bohr parse-labels
    deps:
    - labels
    outs:
    - labels.py:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__datasets_bugginess-train:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      datasets.bugginess-train
    deps:
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - datasets/bugginess-train.py
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.bugginess-train.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_datasets.bugginess-train.json:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__datasets_idans-dataset:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      datasets.idans-dataset
    deps:
    - data/bugginess/train/plain_commits_batch1.csv
    - datasets/idans-dataset.py
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.idans-dataset.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_datasets.idans-dataset.json:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__datasets_1151-commits:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      datasets.1151-commits
    deps:
    - data/bugginess/test/1151-commits.csv
    - datasets/1151-commits.py
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.1151-commits.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_datasets.1151-commits.json:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__datasets_berger:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      datasets.berger
    deps:
    - data/bugginess/test/berger.csv
    - datasets/berger.py
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.berger.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_datasets.berger.json:
        cache: false
  bugginess_apply_heuristics__heuristics_bugginess__datasets_herzig:
    cmd: bohr apply-heuristics bugginess --heuristic-group heuristics.bugginess --dataset
      datasets.herzig
    deps:
    - data/bugginess/test/herzig.csv
    - datasets/herzig.py
    - heuristics/bugginess.py
    - heuristics/keywords
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.herzig.pkl
    metrics:
    - metrics/bugginess/heuristics.bugginess/heuristic_metrics_datasets.herzig.json:
        cache: false
  bugginess_combine_heuristics:
    cmd: bohr apply-heuristics bugginess
    deps:
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.1151-commits.pkl
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.berger.pkl
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.bugginess-train.pkl
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.herzig.pkl
    - generated/bugginess/heuristics.bugginess/heuristic_matrix_datasets.idans-dataset.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/analysis_datasets.1151-commits.csv:
        cache: false
    - generated/bugginess/analysis_datasets.berger.csv:
        cache: false
    - generated/bugginess/analysis_datasets.bugginess-train.csv:
        cache: false
    - generated/bugginess/analysis_datasets.herzig.csv:
        cache: false
    - generated/bugginess/analysis_datasets.idans-dataset.csv:
        cache: false
    - generated/bugginess/heuristic_matrix_datasets.1151-commits.pkl
    - generated/bugginess/heuristic_matrix_datasets.berger.pkl
    - generated/bugginess/heuristic_matrix_datasets.bugginess-train.pkl
    - generated/bugginess/heuristic_matrix_datasets.herzig.pkl
    - generated/bugginess/heuristic_matrix_datasets.idans-dataset.pkl
    metrics:
    - metrics/bugginess/analysis_datasets.1151-commits.json:
        cache: false
    - metrics/bugginess/analysis_datasets.berger.json:
        cache: false
    - metrics/bugginess/analysis_datasets.bugginess-train.json:
        cache: false
    - metrics/bugginess/analysis_datasets.herzig.json:
        cache: false
    - metrics/bugginess/analysis_datasets.idans-dataset.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_datasets.1151-commits.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_datasets.berger.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_datasets.bugginess-train.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_datasets.herzig.json:
        cache: false
    - metrics/bugginess/heuristic_metrics_datasets.idans-dataset.json:
        cache: false
  bugginess_train_label_model:
    cmd: bohr train-label-model bugginess datasets.bugginess-train
    deps:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
    - datasets/1151-commits.py
    - datasets/berger.py
    - datasets/herzig.py
    - generated/bugginess/heuristic_matrix_datasets.1151-commits.pkl
    - generated/bugginess/heuristic_matrix_datasets.berger.pkl
    - generated/bugginess/heuristic_matrix_datasets.bugginess-train.pkl
    - generated/bugginess/heuristic_matrix_datasets.herzig.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/bugginess/label_model.pkl
    metrics:
    - metrics/bugginess/label_model_metrics.json:
        cache: false
  bugginess_label_dataset_datasets_bugginess-train:
    cmd: bohr label-dataset bugginess datasets.bugginess-train
    deps:
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - datasets/bugginess-train.py
    - generated/bugginess/heuristic_matrix_datasets.bugginess-train.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/datasets.bugginess-train.labeled.csv
  bugginess_label_dataset_datasets_idans-dataset:
    cmd: bohr label-dataset bugginess datasets.idans-dataset
    deps:
    - data/bugginess/train/plain_commits_batch1.csv
    - datasets/idans-dataset.py
    - generated/bugginess/heuristic_matrix_datasets.idans-dataset.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/datasets.idans-dataset.labeled.csv
  bugginess_label_dataset_datasets_1151-commits:
    cmd: bohr label-dataset bugginess datasets.1151-commits
    deps:
    - data/bugginess/test/1151-commits.csv
    - datasets/1151-commits.py
    - generated/bugginess/heuristic_matrix_datasets.1151-commits.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/datasets.1151-commits.labeled.csv
  bugginess_label_dataset_datasets_berger:
    cmd: bohr label-dataset bugginess datasets.berger
    deps:
    - data/bugginess/test/berger.csv
    - datasets/berger.py
    - generated/bugginess/heuristic_matrix_datasets.berger.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/datasets.berger.labeled.csv
  bugginess_label_dataset_datasets_herzig:
    cmd: bohr label-dataset bugginess datasets.herzig
    deps:
    - data/bugginess/test/herzig.csv
    - datasets/herzig.py
    - generated/bugginess/heuristic_matrix_datasets.herzig.pkl
    - generated/bugginess/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/datasets.herzig.labeled.csv
  smells_apply_heuristics__heuristics_smells__datasets_smells-train:
    cmd: bohr apply-heuristics smells --heuristic-group heuristics.smells --dataset
      datasets.smells-train
    deps:
    - data/smells/train.csv
    - datasets/smells-train.py
    - heuristics/keywords
    - heuristics/smells.py
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/smells/heuristics.smells/heuristic_matrix_datasets.smells-train.pkl
    metrics:
    - metrics/smells/heuristics.smells/heuristic_metrics_datasets.smells-train.json:
        cache: false
  smells_apply_heuristics__heuristics_smells__datasets_smells-test:
    cmd: bohr apply-heuristics smells --heuristic-group heuristics.smells --dataset
      datasets.smells-test
    deps:
    - data/smells/test.csv
    - datasets/smells-test.py
    - heuristics/keywords
    - heuristics/smells.py
    - labels.py
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/smells/heuristics.smells/heuristic_matrix_datasets.smells-test.pkl
    metrics:
    - metrics/smells/heuristics.smells/heuristic_metrics_datasets.smells-test.json:
        cache: false
  smells_combine_heuristics:
    cmd: bohr apply-heuristics smells
    deps:
    - generated/smells/heuristics.smells/heuristic_matrix_datasets.smells-test.pkl
    - generated/smells/heuristics.smells/heuristic_matrix_datasets.smells-train.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/smells/analysis_datasets.smells-test.csv:
        cache: false
    - generated/smells/analysis_datasets.smells-train.csv:
        cache: false
    - generated/smells/heuristic_matrix_datasets.smells-test.pkl
    - generated/smells/heuristic_matrix_datasets.smells-train.pkl
    metrics:
    - metrics/smells/analysis_datasets.smells-test.json:
        cache: false
    - metrics/smells/analysis_datasets.smells-train.json:
        cache: false
    - metrics/smells/heuristic_metrics_datasets.smells-test.json:
        cache: false
    - metrics/smells/heuristic_metrics_datasets.smells-train.json:
        cache: false
  smells_train_label_model:
    cmd: bohr train-label-model smells datasets.smells-train
    deps:
    - data/smells/test.csv
    - datasets/smells-test.py
    - generated/smells/heuristic_matrix_datasets.smells-test.pkl
    - generated/smells/heuristic_matrix_datasets.smells-train.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - generated/smells/label_model.pkl
    metrics:
    - metrics/smells/label_model_metrics.json:
        cache: false
  smells_label_dataset_datasets_smells-train:
    cmd: bohr label-dataset smells datasets.smells-train
    deps:
    - data/smells/train.csv
    - datasets/smells-train.py
    - generated/smells/heuristic_matrix_datasets.smells-train.pkl
    - generated/smells/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/datasets.smells-train.labeled.csv
  smells_label_dataset_datasets_smells-test:
    cmd: bohr label-dataset smells datasets.smells-test
    deps:
    - data/smells/test.csv
    - datasets/smells-test.py
    - generated/smells/heuristic_matrix_datasets.smells-test.pkl
    - generated/smells/label_model.pkl
    params:
    - bohr.json:
      - bohr_framework_version
    outs:
    - labeled-datasets/datasets.smells-test.labeled.csv
  bugginess_combine_labels_1151-commits:
    cmd: python classifiers/bugginess-transformer/combine_labels.py labeled-datasets/datasets.1151-commits.labeled.csv
      metrics/bugginess/transformer/1151-commits/assigned_labels.csv labeled-datasets/datasets.1151-commits.labeled.both.csv
    deps:
    - classifiers/bugginess-transformer/combine_labels.py
    - labeled-datasets/datasets.1151-commits.labeled.csv
    - metrics/bugginess/transformer/1151-commits/assigned_labels.csv
    outs:
    - labeled-datasets/datasets.1151-commits.labeled.both.csv:
        cache: false
  bugginess_transformer_test_herzig:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/test/herzig.csv
      metrics/bugginess/transformer/herzig
    deps:
    - classifiers/bugginess-transformer/run.py
    - classifiers/bugginess-transformer/test.sh
    - data/bugginess/test/herzig.csv
    - models/config.json
    - models/merges.txt
    - models/pytorch_model.bin
    - models/special_tokens_map.json
    - models/tokenizer_config.json
    - models/training_args.bin
    - models/vocab.json
    - requirements.txt
    metrics:
    - metrics/bugginess/transformer/herzig/eval_results.txt:
        cache: false
  bugginess_transformer_test_1151-commits:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/test/1151-commits.csv
      metrics/bugginess/transformer/1151-commits
    deps:
    - classifiers/bugginess-transformer/run.py
    - classifiers/bugginess-transformer/test.sh
    - data/bugginess/test/1151-commits.csv
    - models/config.json
    - models/merges.txt
    - models/pytorch_model.bin
    - models/special_tokens_map.json
    - models/tokenizer_config.json
    - models/training_args.bin
    - models/vocab.json
    - requirements.txt
    metrics:
    - metrics/bugginess/transformer/1151-commits/eval_results.txt:
        cache: false
  preprocess_smells:
    cmd: bash data-preprocessing/smells.sh
    deps:
    - data-preprocessing/smells.sh
    - downloaded-data/smells-madeyski.csv
    outs:
    - data/smells/test.csv
    - data/smells/train.csv
  preprocess_bugginess_idan:
    cmd: unzip downloaded-data/plain_commits_batch1.csv.zip -d data/bugginess/train
      && rm -r data/bugginess/train/__MACOSX
    deps:
    - downloaded-data/plain_commits_batch1.csv.zip
    outs:
    - data/bugginess/train/plain_commits_batch1.csv
  preprocess_bugginess_test:
    cmd: cp downloaded-data/{1151-commits.csv,berger.csv,herzig.csv} data/bugginess/test
    deps:
    - downloaded-data/1151-commits.csv
    - downloaded-data/berger.csv
    - downloaded-data/herzig.csv
    outs:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
  bugginess_transformer_train:
    cmd: bash classifiers/bugginess-transformer/train.sh labeled-data/bugginess.csv
    deps:
    - classifiers/bugginess-transformer/run.py
    - classifiers/bugginess-transformer/train.sh
    - labeled-datasets/datasets.bugginess-train.labeled.csv
    - requirements.txt
    outs:
    - models/config.json:
        cache: false
    - models/merges.txt:
        cache: false
    - models/pytorch_model.bin
    - models/special_tokens_map.json:
        cache: false
    - models/tokenizer_config.json:
        cache: false
    - models/training_args.bin
    - models/vocab.json:
        cache: false
  bugginess_transformer_label_1151-commits:
    cmd: bash classifiers/bugginess-transformer/label.sh data/bugginess/test/1151-commits.csv
      metrics/bugginess/transformer/1151-commits
    deps:
    - classifiers/bugginess-transformer/label.sh
    - classifiers/bugginess-transformer/run.py
    - data/bugginess/test/1151-commits.csv
    - models/config.json
    - models/merges.txt
    - models/pytorch_model.bin
    - models/special_tokens_map.json
    - models/tokenizer_config.json
    - models/training_args.bin
    - models/vocab.json
    - requirements.txt
    metrics:
    - metrics/bugginess/transformer/1151-commits/assigned_labels.csv:
        cache: false
  preprocess_bugginess_train:
    cmd: 7z x downloaded-data/bugginess_train.7z -odata/bugginess
    deps:
    - downloaded-data/bugginess_train.7z
    outs:
    - data/bugginess/train/bug_sample.csv:
        cache: false
    - data/bugginess/train/bug_sample_files.csv:
        cache: false
    - data/bugginess/train/bug_sample_issues.csv:
        cache: false
  bugginess_transformer_test_berger:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/test/berger.csv
      metrics/bugginess/transformer/berger
    deps:
    - classifiers/bugginess-transformer/run.py
    - classifiers/bugginess-transformer/test.sh
    - data/bugginess/test/berger.csv
    - models/config.json
    - models/merges.txt
    - models/pytorch_model.bin
    - models/special_tokens_map.json
    - models/tokenizer_config.json
    - models/training_args.bin
    - models/vocab.json
    - requirements.txt
    metrics:
    - metrics/bugginess/transformer/berger/eval_results.txt:
        cache: false
