stages:
  parse_labels:
    cmd: bohr parse-labels
    deps:
    - labels
    outs:
    - labels.py:
        cache: false
  preprocess_bugginess_train:
    cmd: 7z x downloaded-data/bugginess_train.7z -odata/bugginess
    deps:
    - downloaded-data/bugginess_train.7z
    outs:
    - data/bugginess/train/bug_sample.csv:
        cache: false
    - data/bugginess/train/bug_sample_files.csv:
        cache: false
    - data/bugginess/train/bug_sample_issues.csv:
        cache: false
  preprocess_bugginess_test:
    cmd: cp downloaded-data/{1151-commits.csv,berger.csv,herzig.csv} data/bugginess/test
    deps:
    - downloaded-data/1151-commits.csv
    - downloaded-data/berger.csv
    - downloaded-data/herzig.csv
    outs:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
  preprocess_smells:
    cmd: bash data-preprocessing/smells.sh
    deps:
    - data-preprocessing/smells.sh
    - downloaded-data/smells-madeyski.csv
    outs:
    - data/smells/test.csv
    - data/smells/train.csv
  bugginess_apply_heuristics:
    cmd: bohr apply-heuristics bugginess
    deps:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - dataloaders/1151-commits.py
    - dataloaders/berger.py
    - dataloaders/bugginess-train.py
    - dataloaders/herzig.py
    - heuristics
    - labels.py
    - tasks/bugginess.py
    outs:
    - generated/bugginess/analysis_1151-commits.csv:
        cache: false
    - generated/bugginess/analysis_berger.csv:
        cache: false
    - generated/bugginess/analysis_herzig.csv:
        cache: false
    - generated/bugginess/analysis_train.csv:
        cache: false
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/heuristic_matrix_train.pkl
    metrics:
    - metrics/bugginess/analysis_1151-commits.json:
        cache: false
    - metrics/bugginess/analysis_berger.json:
        cache: false
    - metrics/bugginess/analysis_herzig.json:
        cache: false
    - metrics/bugginess/analysis_train.json:
        cache: false
    - metrics/bugginess/heuristic_metrics.json:
        cache: false
  bugginess_train_label_model:
    cmd: bohr train-label-model bugginess
    deps:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
    - dataloaders/1151-commits.py
    - dataloaders/berger.py
    - dataloaders/herzig.py
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/heuristic_matrix_train.pkl
    - tasks/bugginess.py
    outs:
    - generated/bugginess/label_model.pkl
    metrics:
    - metrics/bugginess/label_model_metrics.json:
        cache: false
  bugginess_label_dataset:
    cmd: bohr label-dataset bugginess bugginess-train
    deps:
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - dataloaders/bugginess-train.py
    - generated/bugginess/heuristic_matrix_train.pkl
    - tasks/bugginess.py
    outs:
    - labeled-data/bugginess.csv
  smells_apply_heuristics:
    cmd: bohr apply-heuristics smells
    deps:
    - data/smells/test.csv
    - data/smells/train.csv
    - dataloaders/smells-test.py
    - dataloaders/smells-train.py
    - heuristics
    - labels.py
    - tasks/smells.py
    outs:
    - generated/smells/analysis_smells-test.csv:
        cache: false
    - generated/smells/analysis_train.csv:
        cache: false
    - generated/smells/heuristic_matrix_smells-test.pkl
    - generated/smells/heuristic_matrix_train.pkl
    metrics:
    - metrics/smells/analysis_smells-test.json:
        cache: false
    - metrics/smells/analysis_train.json:
        cache: false
    - metrics/smells/heuristic_metrics.json:
        cache: false
  smells_train_label_model:
    cmd: bohr train-label-model smells
    deps:
    - data/smells/test.csv
    - dataloaders/smells-test.py
    - generated/smells/heuristic_matrix_smells-test.pkl
    - generated/smells/heuristic_matrix_train.pkl
    - tasks/smells.py
    outs:
    - generated/smells/label_model.pkl
    metrics:
    - metrics/smells/label_model_metrics.json:
        cache: false
  smells_label_dataset:
    cmd: bohr label-dataset smells smells-train
    deps:
    - data/smells/train.csv
    - dataloaders/smells-train.py
    - generated/smells/heuristic_matrix_train.pkl
    - tasks/smells.py
    outs:
    - labeled-data/smells.csv
