stages:
  parse_labels:
    cmd: bohr parse-labels
    deps:
    - labels
    outs:
    - labels.py:
        cache: false
  preprocess_bugginess_train:
    cmd: 7z x downloaded-data/bugginess_train.7z -odata/bugginess
    deps:
    - downloaded-data/bugginess_train.7z
    outs:
    - data/bugginess/train/bug_sample.csv:
        cache: false
    - data/bugginess/train/bug_sample_files.csv:
        cache: false
    - data/bugginess/train/bug_sample_issues.csv:
        cache: false
  preprocess_bugginess_test:
    cmd: cp downloaded-data/{1151-commits.csv,berger.csv,herzig.csv} data/bugginess/test
    deps:
    - downloaded-data/1151-commits.csv
    - downloaded-data/berger.csv
    - downloaded-data/herzig.csv
    outs:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
  preprocess_smells:
    cmd: bash data-preprocessing/smells.sh
    deps:
    - data-preprocessing/smells.sh
    - downloaded-data/smells-madeyski.csv
    outs:
    - data/smells/test.csv
    - data/smells/train.csv
  bugginess_apply_heuristics:
    cmd: bohr apply-heuristics bugginess
    deps:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - datasets/1151-commits.py
    - datasets/berger.py
    - datasets/bugginess-train.py
    - datasets/herzig.py
    - heuristics
    - labels.py
    outs:
    - generated/bugginess/analysis_datasets.1151-commits.csv:
        cache: false
    - generated/bugginess/analysis_datasets.berger.csv:
        cache: false
    - generated/bugginess/analysis_datasets.herzig.csv:
        cache: false
    - generated/bugginess/analysis_train.csv:
        cache: false
    - generated/bugginess/heuristic_matrix_datasets.1151-commits.pkl
    - generated/bugginess/heuristic_matrix_datasets.berger.pkl
    - generated/bugginess/heuristic_matrix_datasets.herzig.pkl
    - generated/bugginess/heuristic_matrix_train.pkl
    metrics:
    - metrics/bugginess/analysis_datasets.1151-commits.json:
        cache: false
    - metrics/bugginess/analysis_datasets.berger.json:
        cache: false
    - metrics/bugginess/analysis_datasets.herzig.json:
        cache: false
    - metrics/bugginess/analysis_train.json:
        cache: false
    - metrics/bugginess/heuristic_metrics.json:
        cache: false
    params:
    - bohr.json:
      - bohr_framework_version
  bugginess_train_label_model:
    cmd: bohr train-label-model bugginess
    deps:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
    - datasets/1151-commits.py
    - datasets/berger.py
    - datasets/herzig.py
    - generated/bugginess/heuristic_matrix_datasets.1151-commits.pkl
    - generated/bugginess/heuristic_matrix_datasets.berger.pkl
    - generated/bugginess/heuristic_matrix_datasets.herzig.pkl
    - generated/bugginess/heuristic_matrix_train.pkl
    outs:
    - generated/bugginess/label_model.pkl
    metrics:
    - metrics/bugginess/label_model_metrics.json:
        cache: false
    params:
    - bohr.json:
      - bohr_framework_version
  bugginess_label_dataset:
    cmd: bohr label-dataset bugginess datasets.bugginess-train
    deps:
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - datasets/bugginess-train.py
    - generated/bugginess/heuristic_matrix_train.pkl
    outs:
    - labeled-data/bugginess.csv
    params:
    - bohr.json:
      - bohr_framework_version
  smells_apply_heuristics:
    cmd: bohr apply-heuristics smells
    deps:
    - data/smells/test.csv
    - data/smells/train.csv
    - datasets/smells-test.py
    - datasets/smells-train.py
    - heuristics
    - labels.py
    outs:
    - generated/smells/analysis_datasets.smells-test.csv:
        cache: false
    - generated/smells/analysis_train.csv:
        cache: false
    - generated/smells/heuristic_matrix_datasets.smells-test.pkl
    - generated/smells/heuristic_matrix_train.pkl
    metrics:
    - metrics/smells/analysis_datasets.smells-test.json:
        cache: false
    - metrics/smells/analysis_train.json:
        cache: false
    - metrics/smells/heuristic_metrics.json:
        cache: false
    params:
    - bohr.json:
      - bohr_framework_version
  smells_train_label_model:
    cmd: bohr train-label-model smells
    deps:
    - data/smells/test.csv
    - datasets/smells-test.py
    - generated/smells/heuristic_matrix_datasets.smells-test.pkl
    - generated/smells/heuristic_matrix_train.pkl
    outs:
    - generated/smells/label_model.pkl
    metrics:
    - metrics/smells/label_model_metrics.json:
        cache: false
    params:
    - bohr.json:
      - bohr_framework_version
  smells_label_dataset:
    cmd: bohr label-dataset smells datasets.smells-train
    deps:
    - data/smells/train.csv
    - datasets/smells-train.py
    - generated/smells/heuristic_matrix_train.pkl
    outs:
    - labeled-data/smells.csv
    params:
    - bohr.json:
      - bohr_framework_version
  bugginess_transformer_train:
    cmd: bash classifiers/bugginess-transformer/train.sh labeled-data/bugginess.csv
    deps:
      - classifiers/bugginess-transformer/train.sh
      - classifiers/bugginess-transformer/run.py
      - requirements.txt
      - labeled-data/bugginess.csv
    outputs:
      - model/pytorch_model.bin
      - model/training_args.bin
      - model/config.json:
          - cache: false
      - model/merges.txt:
          - cache: false
      - model/special_tokens_map.json:
          - cache: false
      - model/tokenizer_config.json:
          - cache: false
      - model/vocab.json:
          - cache: false
  bugginess_transformer_test_1151:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/test/1151-commits.csv metrics/bugginess/transformer/1151-commits
    deps:
      - classifiers/bugginess-transformer/train.sh
      - classifiers/bugginess-transformer/run.py
      - requirements.txt
      - data/bugginess/test/1151-commits.csv
    metrics:
      - metrics/bugginess/transformer/1151-commits/eval_results.txt:
          cache: false
  bugginess_transformer_test_1151-commits:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/test/1151-commits.csv metrics/bugginess/transformer/1151-commits
    deps:
      - classifiers/bugginess-transformer/test.sh
      - classifiers/bugginess-transformer/run.py
      - requirements.txt
      - data/bugginess/test/1151-commits.csv
    metrics:
      - metrics/bugginess/transformer/1151-commits/eval_results.txt:
          cache: false
  bugginess_transformer_test_berger:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/test/berger.csv metrics/bugginess/transformer/berger
    deps:
      - classifiers/bugginess-transformer/test.sh
      - classifiers/bugginess-transformer/run.py
      - requirements.txt
      - data/bugginess/test/berger.csv
    metrics:
      - metrics/bugginess/transformer/berger/eval_results.txt:
          cache: false
  bugginess_transformer_test_herzig:
    cmd: bash classifiers/bugginess-transformer/test.sh data/bugginess/test/herzig.csv metrics/bugginess/transformer/herzig
    deps:
      - classifiers/bugginess-transformer/test.sh
      - classifiers/bugginess-transformer/run.py
      - requirements.txt
      - data/bugginess/test/herzig.csv
    metrics:
      - metrics/bugginess/transformer/herzig/eval_results.txt:
          cache: false
