stages:
  extract_train_data:
    cmd: 7z x downloaded-data/b_b.7z -odata
    deps:
    - downloaded-data/b_b.7z
    outs:
    - data/train:
        cache: false
  apply_heuristics:
    cmd: python bohr/pipeline/apply_heuristics.py
    deps:
    - bohr/heuristics
    - bohr/pipeline/apply_heuristics.py
    - data/train
    - data/test
    outs:
    - generated/heuristic_matrix_train.pkl
    - generated/heuristic_matrix_herzig.pkl
    - generated/heuristic_matrix_berger.pkl
    - generated/heuristic_matrix_1151_commits.pkl
    - generated/analysis_train.csv:
        cache: false
    - generated/analysis_herzig.csv:
        cache: false
    - generated/analysis_berger.csv:
        cache: false
    - generated/analysis_1151_commits.csv:
        cache: false
    metrics:
    - heuristic_metrics.json:
        cache: false
  train_label_model:
    cmd: python bohr/pipeline/train_label_model.py
    deps:
    - bohr/pipeline/train_label_model.py
    - generated/heuristic_matrix_train.pkl
    - generated/heuristic_matrix_herzig.pkl
    - generated/heuristic_matrix_berger.pkl
    - generated/heuristic_matrix_1151_commits.pkl
    - data/train
    - data/test
    outs:
    - generated/label_model.pkl
    metrics:
    - label_model_metrics.json:
        cache: false

