stages:
  parse_labels:
    cmd: python bohr/framework/pipeline/parse_labels.py
    deps:
    - bohr/framework #framework is an exception for now but for everything else we dvc-track separate files where possible
    - bohr/labels
    outs:
    - bohr/labels.py:
        cache: false
  preprocess_bugginess_train:
    cmd: 7z x downloaded-data/bugginess_train.7z -odata/bugginess
    deps:
    - downloaded-data/bugginess_train.7z
    outs:
    - data/bugginess/train/bug_sample.csv:
        cache: false
    - data/bugginess/train/bug_sample_files.csv:
        cache: false
    - data/bugginess/train/bug_sample_issues.csv:
        cache: false
  preprocess_bugginess_test:
    cmd: cp downloaded-data/{1151-commits.csv,berger.csv,herzig.csv} data/bugginess/test
    deps:
      - downloaded-data/1151-commits.csv
      - downloaded-data/berger.csv
      - downloaded-data/herzig.csv
    outs:
      - data/bugginess/test/1151-commits.csv
      - data/bugginess/test/berger.csv
      - data/bugginess/test/herzig.csv
  preprocess_smells:
    cmd: bash data-preprocessing/smells.sh
    deps:
      - data-preprocessing/smells.sh
      - downloaded-data/smells-madeyski.csv
    outs:
      - data/smells/test.csv
      - data/smells/train.csv
  apply_heuristics_bugginess:
    cmd: python bohr/framework/pipeline/apply_heuristics.py bugginess
    deps:
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - bohr/framework
    - bohr/heuristics
    - bohr/labels.py
    - bohr/tasks/bugginess.py
    outs:
    - generated/bugginess/analysis_1151-commits.csv:
        cache: false
    - generated/bugginess/analysis_berger.csv:
        cache: false
    - generated/bugginess/analysis_herzig.csv:
        cache: false
    - generated/bugginess/analysis_train.csv:
        cache: false
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/heuristic_matrix_train.pkl
    metrics:
    - metrics/bugginess/analysis_1151-commits.json:
        cache: false
    - metrics/bugginess/analysis_berger.json:
        cache: false
    - metrics/bugginess/analysis_herzig.json:
        cache: false
    - metrics/bugginess/analysis_train.json:
        cache: false
    - metrics/bugginess/heuristic_metrics.json:
        cache: false
  train_label_model_bugginess:
    cmd: python bohr/framework/pipeline/train_label_model.py bugginess
    deps:
    - bohr/framework
    - data/bugginess/test/1151-commits.csv
    - data/bugginess/test/berger.csv
    - data/bugginess/test/herzig.csv
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - generated/bugginess/heuristic_matrix_1151-commits.pkl
    - generated/bugginess/heuristic_matrix_berger.pkl
    - generated/bugginess/heuristic_matrix_herzig.pkl
    - generated/bugginess/heuristic_matrix_train.pkl
    outs:
    - generated/bugginess/label_model.pkl
    metrics:
    - metrics/bugginess/label_model_metrics.json:
        cache: false
  label_dataset_bugginess:
    cmd: python bohr/framework/pipeline/label_dataset.py bugginess bugginess-train
    deps:
    - bohr/framework
    - data/bugginess/train/bug_sample.csv
    - data/bugginess/train/bug_sample_files.csv
    - data/bugginess/train/bug_sample_issues.csv
    - generated/bugginess/heuristic_matrix_train.pkl
    outs:
    - labeled-data/bugginess-train.csv
  apply_heuristics_bugginess_10k:
    cmd: python bohr/framework/pipeline/apply_heuristics.py bugginess-10k
    deps:
      - data/bugginess/test/1151-commits.csv
      - data/bugginess/test/berger.csv
      - data/bugginess/test/herzig.csv
      - data/bugginess/train/bug_sample.csv
      - data/bugginess/train/bug_sample_files.csv
      - data/bugginess/train/bug_sample_issues.csv
      - bohr/framework
      - bohr/heuristics
      - bohr/labels.py
      - bohr/tasks/bugginess-10k.py
    outs:
      - generated/bugginess-10k/analysis_1151-commits.csv:
          cache: false
      - generated/bugginess-10k/analysis_berger.csv:
          cache: false
      - generated/bugginess-10k/analysis_herzig.csv:
          cache: false
      - generated/bugginess-10k/analysis_train.csv:
          cache: false
      - generated/bugginess-10k/heuristic_matrix_1151-commits.pkl
      - generated/bugginess-10k/heuristic_matrix_berger.pkl
      - generated/bugginess-10k/heuristic_matrix_herzig.pkl
      - generated/bugginess-10k/heuristic_matrix_train.pkl
    metrics:
      - metrics/bugginess-10k/analysis_1151-commits.json:
          cache: false
      - metrics/bugginess-10k/analysis_berger.json:
          cache: false
      - metrics/bugginess-10k/analysis_herzig.json:
          cache: false
      - metrics/bugginess-10k/analysis_train.json:
          cache: false
      - metrics/bugginess-10k/heuristic_metrics.json:
          cache: false
  train_label_model_bugginess_10k:
    cmd: python bohr/framework/pipeline/train_label_model.py bugginess-10k
    deps:
      - bohr/framework
      - data/bugginess/test/1151-commits.csv
      - data/bugginess/test/berger.csv
      - data/bugginess/test/herzig.csv
      - data/bugginess/train/bug_sample.csv
      - data/bugginess/train/bug_sample_files.csv
      - data/bugginess/train/bug_sample_issues.csv
      - generated/bugginess-10k/heuristic_matrix_1151-commits.pkl
      - generated/bugginess-10k/heuristic_matrix_berger.pkl
      - generated/bugginess-10k/heuristic_matrix_herzig.pkl
      - generated/bugginess-10k/heuristic_matrix_train.pkl
    outs:
      - generated/bugginess-10k/label_model.pkl
    metrics:
      - metrics/bugginess-10k/label_model_metrics.json:
          cache: false
  label_dataset_bugginess_10k:
    cmd: python bohr/framework/pipeline/label_dataset.py bugginess-10k bugginess-train-10k
    deps:
      - bohr/framework
      - data/bugginess/train/bug_sample.csv
      - data/bugginess/train/bug_sample_files.csv
      - data/bugginess/train/bug_sample_issues.csv
      - generated/bugginess-10k/heuristic_matrix_train.pkl
    outs:
      - labeled-data/bugginess-train-10k.csv
  apply_heuristics_smells:
    cmd: python bohr/framework/pipeline/apply_heuristics.py smells
    deps:
      - bohr/dataloaders
      - bohr/framework
      - bohr/heuristics
      - bohr/labels.py
      - data/smells
      - bohr/tasks/smells.py
    outs:
      - generated/smells/analysis_smells-test.csv:
          cache: false
      - generated/smells/analysis_train.csv:
          cache: false
      - generated/smells/heuristic_matrix_smells-test.pkl
      - generated/smells/heuristic_matrix_train.pkl
    metrics:
      - metrics/smells/analysis_smells-test.json:
          cache: false
      - metrics/smells/analysis_train.json:
          cache: false
      - metrics/smells/heuristic_metrics.json:
          cache: false
  train_label_model_smells:
    cmd: python bohr/framework/pipeline/train_label_model.py smells
    deps:
      - bohr/dataloaders
      - bohr/framework
      - bohr/tasks/smells.py
      - data/smells
      - generated/smells/heuristic_matrix_smells-test.pkl
      - generated/smells/heuristic_matrix_train.pkl
    outs:
      - generated/smells/label_model.pkl
    metrics:
      - metrics/smells/label_model_metrics.json:
          cache: false
  label_dataset_bugginess_smells:
    cmd: python bohr/framework/pipeline/label_dataset.py smells smells-train
    deps:
      - bohr/dataloaders
      - bohr/framework
      - bohr/tasks/smells.py
      - data/smells/train.csv
      - generated/smells/heuristic_matrix_train.pkl
    outs:
      - labeled-data/smells-train.csv
  apply_heuristics_smells_10:
    cmd: python bohr/framework/pipeline/apply_heuristics.py smells_10
    deps:
      - bohr/dataloaders
      - bohr/framework
      - bohr/heuristics
      - bohr/labels.py
      - data/smells/test.csv
      - data/smells/train.csv
      - bohr/tasks/smells_10.py
    outs:
      - generated/smells_10/analysis_smells-test_10.csv:
          cache: false
      - generated/smells_10/analysis_train.csv:
          cache: false
      - generated/smells_10/heuristic_matrix_smells-test_10.pkl
      - generated/smells_10/heuristic_matrix_train.pkl
    metrics:
      - metrics/smells_10/analysis_smells-test_10.json:
          cache: false
      - metrics/smells_10/analysis_train.json:
          cache: false
      - metrics/smells_10/heuristic_metrics.json:
          cache: false
  train_label_smells_10:
    cmd: python bohr/framework/pipeline/train_label_model.py smells_10
    deps:
      - bohr/dataloaders
      - bohr/framework
      - bohr/tasks/smells_10.py
      - data/smells/test.csv
      - data/smells/train.csv
      - generated/smells_10/heuristic_matrix_smells-test_10.pkl
      - generated/smells_10/heuristic_matrix_train.pkl
    outs:
      - generated/smells_10/label_model.pkl
    metrics:
      - metrics/smells_10/label_model_metrics.json:
          cache: false
  label_dataset_smells_10:
    cmd: python bohr/framework/pipeline/label_dataset.py smells_10 smells-train_10
    deps:
      - bohr/dataloaders
      - bohr/framework
      - bohr/tasks/smells_10.py
      - data/smells/train.csv
      - generated/smells_10/heuristic_matrix_train.pkl
    outs:
      - labeled-data/smells-train_10.csv
  all_short_stages:
    cmd: echo "Running all short stages"
    deps:
      - generated/bugginess-10k/label_model.pkl
      - generated/smells_10/label_model.pkl
      - labeled-data/bugginess-train-10k.csv
      - labeled-data/smells-train_10.csv
