from bohr.heuristics.templates import regex_git2__for_commit_message, keyword_lookup_template, ISSUE_CONTENTS, \
    ISSUE_LABELS, COMMIT_MESSAGE
from bohr.snorkel_utils import BUG

heuristics = [
    regex_git2__for_commit_message
] + keyword_lookup_template(label=BUG, terms=[
    'bad',
    'broken',
    'bug',
    'bugg',
    'concurr',
    'correct',
    'crash',
    'defect',
    'error',
    'fail',
    'failur',
    'fix',
    'hotfix',
    'invalid',
    'issue',
    'quickfix',
    'unknown',
]) + keyword_lookup_template(label=BUG, terms=[
    'except',
], only_full_word=False) + keyword_lookup_template(label=BUG, terms=[
    'close',
    'fault',
    'handl',
    'minor',
], restrict_to_fields=[ISSUE_CONTENTS, ISSUE_LABELS]) + keyword_lookup_template(label=BUG, terms=[
    'logic',
    'merg',
], restrict_to_fields=[ISSUE_LABELS]) + keyword_lookup_template(label=BUG, terms=[
    'correctli',
    'corrupt',
    'deadlock',
    'dead lock',
    'endless',
    'ensur',
    'garbag',
    'incorrect',
    'leak',
    'fix and test',
    'incomplet',
    'inconsist',
    'infinit',
    'loop',
    'mistak',
    'not return',
    'not work',
    'prevent',
    'problem',
    'properli',
    'race condit',
    'repair',
    'small fix',
    'solv',
    'threw',
    'throw',
    'timeout',
    'unabl',
    'unclos',
    'unexpect',
    'unsynchron',
    'wrong',
], restrict_to_fields=[COMMIT_MESSAGE, ISSUE_CONTENTS]) + keyword_lookup_template(label=BUG, terms=[
    'disabl',
    'fix & test',
    'not log',
    'patch',
    'resolv',
], restrict_to_fields=[ISSUE_CONTENTS]) + keyword_lookup_template(label=BUG, terms=[
    'nullpointer',
    'null pointer',
    'outofbound',
    'out of bound',
], restrict_to_fields=[COMMIT_MESSAGE, ISSUE_CONTENTS], only_full_word=False)
