name: build-docker
on: [pull_request, push]
jobs:
  update-docker-container:
    runs-on: [ubuntu-latest]
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: build-container
        run: bash bin/update-docker.sh

