name: check-dvc-clean
on:
  push:
    branches: [ master ]
jobs:
  check-dvc-clean:
    defaults:
      run:
        shell: bash -lieo pipefail {0}
    runs-on: self-hosted
    strategy:
      matrix:
        python:
          - 3.8.0
    container: giganticode/bohr-cml-base:latest
    env:
      DVC_IRONSPEED_USERNAME: ${{ secrets.DVC_IRONSPEED_USERNAME }}
      DVC_IRONSPEED_PASSWORD: ${{ secrets.DVC_IRONSPEED_PASSWORD }}
      PYTHONPATH: /usr/src/bohr-framework/
    steps:
      - name: update-git
        run: |
          apt-get install software-properties-common -y
          add-apt-repository ppa:git-core/ppa -y
          apt-get update
          apt-get install git -y
          git --version
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: setup-dvc
        run: |
          pip install --upgrade pip wheel setuptools
          BOHR_VERSION="$(bash bin/bohr-version.sh)"
          pip install "dvc[all]==$(curl -L https://raw.githubusercontent.com/giganticode/bohr-framework/$BOHR_VERSION/DVC_VERSION)"
          dvc --version
          dvc remote modify --local ironspeed user $DVC_IRONSPEED_USERNAME
          dvc remote modify --local ironspeed password $DVC_IRONSPEED_PASSWORD
      - name: reproduce-and-check-status
        run: |
          dvc pull -r ironspeed
          dvc repro preprocess_bugginess_train
          dvc status
          dvc status -q
