name: check-dvc-clean
on:
  push:
    branches: [ master ]
jobs:
  check-dvc-clean:
    defaults:
      run:
        shell: bash -lieo pipefail {0}
    runs-on: self-hosted
    strategy:
      matrix:
        python:
          - 3.8.0
    container: giganticode/bohr-cml-base:latest
    env:
      DVC_SQUIRREL_USERNAME: ${{ secrets.DVC_SQUIRREL_USERNAME }}
      DVC_SQUIRREL_PASSWORD: ${{ secrets.DVC_SQUIRREL_PASSWORD }}
      PYTHONPATH: '/__w/bohr/bohr'
    steps:
      - name: update-git
        run: |
          apt-get install software-properties-common -y
          add-apt-repository ppa:git-core/ppa -y
          apt-get update
          apt-get install git -y
          git --version
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: setup-bohr
        run: |
          bin/setup-bohr.sh $SOFTWARE_DIR
          dvc remote modify --local squirrel user DVC_SQUIRREL_USERNAME
          dvc remote modify --local squirrel password DVC_SQUIRREL_PASSWORD
      - name: checking-env-setup
        run: |
          which bohr
          bohr --version
          dvc --version
          pwd
          ls
          python -c "import sys; print(sys.path)"
      - name: reproduce-and-check-status
        run: |
          dvc pull -r squirrel
          bohr repro --only-transient
          bohr status
          dvc status -q
