name: check-dvc-clean
on: [pull_request]
jobs:
  check-dvc-clean:
    defaults:
      run:
        shell: bash -lieo pipefail {0}
    runs-on: self-hosted
    strategy:
      matrix:
        python:
          - 3.8.0
    container: giganticode/bohr-cml-base:latest
    env:
      DVC_IRONSPEED_USERNAME: ${{ secrets.DVC_IRONSPEED_USERNAME }}
      DVC_IRONSPEED_PASSWORD: ${{ secrets.DVC_IRONSPEED_PASSWORD }}
      PYTHONPATH: /usr/src/bohr
    steps:
      - uses: actions/checkout@v2
      - name: setup-dvc
        run: |
          pip install --upgrade pip wheel setuptools
          BOHR_VERSION="$(bash bin/bohr-version.sh)"
          pip install "dvc[all]==$(curl -L https://raw.githubusercontent.com/giganticode/bohr-framework/$BOHR_VERSION/DVC_VERSION)"
          dvc --version
          dvc remote modify --local ironspeed user $DVC_IRONSPEED_USERNAME
          dvc remote modify --local ironspeed password $DVC_IRONSPEED_PASSWORD
      - name: reproduce-and-check-status
        run: |
          dvc pull -r ironspeed
          dvc repro preprocess_bugginess_train
          dvc status
          dvc status -q
