name: check-dvc-clean
on:
  push:
    branches: [ master ]
jobs:
  check-dvc-clean:
    runs-on: self-hosted
    container: docker://giganticode/bohr-cml-base:latest
    steps:
      - uses: actions/checkout@v2
      - name: check-dvc-clean
        env:
          DVC_IRONSPEED_PASSWORD: ${{ secrets.DVC_IRONSPEED_PASSWORD }}
          PYTHONPATH: /usr/src/bohr/
        run: |
          sudo apt-get update && sudo apt-get install p7zip-full
          dvc remote modify --local ironspeed user hbabii
          dvc remote modify --local ironspeed password $DVC_IRONSPEED_PASSWORD
          dvc pull
          dvc repro preprocess_bugginess_train
          dvc status
          dvc status -q
