name: check-dvc-clean
on:
  push:
    branches: [ master ]
jobs:
  check-dvc-clean:
    runs-on: self-hosted
    container: docker://giganticode/bohr-cml-base:latest
    steps:
      - uses: actions/checkout@v2
      - name: dvc-status
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          PYTHONPATH: /usr/src/bohr/
        run: |
          sudo apt-get update && sudo apt-get install p7zip-full
          dvc pull
          dvc repro extract_train_data
          dvc status
          dvc status -q
