name: pull_request
on: [pull_request]
jobs:
  reproduce-pipeline: #TODO find a way to reuse stages: https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/12
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python:
          - 3.8.0
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      PYTHONPATH: /home/runner/work/bohr/bohr
      SOFTWARE_DIR: /home/runner/work/bohr/tools
    steps:
      - name: update-git
        run: |
          sudo apt-get install software-properties-common
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install git -y
          git --version
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pull auto-commited dvc output
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          git fetch origin pull/$PR_NUMBER/head:pr/$PR_NUMBER
          git checkout pr/$PR_NUMBER
          echo "HEAD is $(git rev-parse --short HEAD)"
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: setup-bohr
        run: |
          bin/setup-bohr.sh $SOFTWARE_DIR
          cat .dvc/config
      - name: repro
        run: |
          bohr repro
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --cached --exit-code || git commit -m "dvc: update outputs and hashsum"
      - name: Push to dvc
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          pip install 'dvc[gdrive]'
          dvc push -r gdrive # github container only can have access to gdrive remote (others need to be accessed using VPN)
      - name: Check dvc status
        run: dvc status -r gdrive
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
      - uses: iterative/setup-cml@v1
      - name: post_metrics
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --prune
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md
  copy-dvc-data-to-everywhere:
    needs: reproduce-pipeline
    runs-on: self-hosted
    strategy:
      matrix:
        python:
          - 3.8.0
    defaults:
      run:
        shell: bash -lieo pipefail {0}
    container: giganticode/bohr-cml-base:latest
    env:
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      DVC_SQUIRREL_USERNAME: ${{ secrets.DVC_SQUIRREL_USERNAME }}
      DVC_SQUIRREL_PASSWORD: ${{ secrets.DVC_SQUIRREL_PASSWORD }}
      PYTHONPATH: /usr/src/bohr/
    steps:
      - name: update-git
        run: |
          apt-get install software-properties-common -y
          add-apt-repository ppa:git-core/ppa -y
          apt-get update
          apt-get install git -y
          git --version
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pull auto-commited dvc output
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          git fetch origin pull/$PR_NUMBER/head:pr/$PR_NUMBER
          git checkout pr/$PR_NUMBER
          echo "HEAD is $(git rev-parse --short HEAD)"
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: setup-dvc
        run: |
          dvc --version
          dvc remote modify --local squirrel user $DVC_SQUIRREL_USERNAME
          dvc remote modify --local squirrel password $DVC_SQUIRREL_PASSWORD
      - name: move-from-gdrive-to-squirrel
        run: |
          dvc pull -r gdrive
          dvc push -r squirrel # make it available to the world
          dvc gc --cloud -r gdrive --workspace -f
