name: pull_request
on: [pull_request]
jobs:
  bugginess-short:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -lieo pipefail {0}
        working-directory: /usr/src/bohr
    container: giganticode/bohr-cml-base:latest
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      DVC_IRONSPEED_USERNAME: ${{ secrets.DVC_IRONSPEED_USERNAME }}
      DVC_IRONSPEED_PASSWORD: ${{ secrets.DVC_IRONSPEED_PASSWORD }}
      PYTHONPATH: /usr/src/bohr/
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: update-base-ref
        run: |
          git checkout $GITHUB_BASE_REF
          git pull
      - name: checkout-pull-request
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          git fetch origin pull/$PR_NUMBER/head:pr/$PR_NUMBER
          git checkout pr/$PR_NUMBER
          pip install -r requirements.txt
      - name: build-image
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && bash bin/update-docker.sh "origin/$GITHUB_BASE_REF"
      - name: install-dvc
        run: |
          pip install "dvc[ssh]==$(cat DVC_VERSION)"
          dvc --version
          dvc remote modify --local ironspeed user $DVC_IRONSPEED_USERNAME
          dvc remote modify --local ironspeed password $DVC_IRONSPEED_PASSWORD
      - name: reproduce-bugginess
        run: |
          dvc pull -r ironspeed downloaded-data/bugginess_train.7z downloaded-data/berger.csv downloaded-data/herzig.csv downloaded-data/1151-commits.csv
          dvc repro bugginess-10k_label_dataset
      - name: reproduce-smells
        run: |
          dvc pull -r ironspeed downloaded-data/smells-madeyski.csv
          dvc repro smells_10_label_dataset smells_10_train_label_model
      - name: report-metrics
        run: |
          git fetch --prune
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md
  reproduce-pipeline: #TODO find a way to reuse stages: https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/12
    runs-on: [ubuntu-latest]
    needs: bugginess-short
    strategy:
      matrix:
        python:
          - 3.8.0
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      PYTHONPATH: /home/runner/work/bohr/bohr
      SOFTWARE_DIR: /home/runner/work/bohr/tools
    steps:
      - name: update-git
        run: |
          sudo apt-get install software-properties-common
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install git -y
          git --version
      - name: install-cml
        run: |
          curl -sL https://deb.nodesource.com/setup_15.x | sudo bash
          sudo apt-get update
          sudo apt-get install -y nodejs
          sudo node -v
          sudo npm -v
          sudo npm i -g @dvcorg/cml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip  # upgrade pip after installing python
      - name: install-dvc
        run: |
          pip install "dvc[all]==$(cat DVC_VERSION)"
          dvc --version
      - name: reproduce-transient-stages
        run: |
          dvc pull -r gdrive
          dvc repro preprocess_bugginess_train
      - name: install-tools
        working-directory: /home/runner/work/bohr/bohr
        run: dvc status -q || sudo bash tools/install-refactoring-miner.sh $SOFTWARE_DIR
      - name: install-dependencies
        run: dvc status -q || (pip install Cython==0.29.21 && pip install -r requirements.txt)
      - name: repro
        run: |
          dvc repro
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --cached --exit-code || git commit -m "Add dvc outputs"
      - name: Push to dvc
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run:
          dvc push -r gdrive
      - name: Clean up dvc remote
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run:
          dvc gc --cloud -r gdrive --workspace --all-tags --all-branches -f
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
      - name: post_metrics
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --prune
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md
  copy-dvc-data-to-everywhere:
    needs: reproduce-pipeline
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -lieo pipefail {0}
    container: giganticode/bohr-cml-base:latest
    env:
      GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      DVC_IRONSPEED_USERNAME: ${{ secrets.DVC_IRONSPEED_USERNAME }}
      DVC_IRONSPEED_PASSWORD: ${{ secrets.DVC_IRONSPEED_PASSWORD }}
      DVC_ACTARUS_USERNAME: ${{ secrets.DVC_ACTARUS_USERNAME }}
      DVC_ACTARUS_PASSWORD: ${{ secrets.DVC_ACTARUS_PASSWORD }}
      PYTHONPATH: /usr/src/bohr/
    steps:
      - name: update-git
        run: |
          apt-get install software-properties-common -y
          add-apt-repository ppa:git-core/ppa -y
          apt-get update
          apt-get install git -y
          git --version
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install-dvc
        run: |
          pip install "dvc[all]==$(cat DVC_VERSION)"
          dvc --version
          dvc remote modify --local ironspeed user $DVC_IRONSPEED_USERNAME
          dvc remote modify --local ironspeed password $DVC_IRONSPEED_PASSWORD
          dvc remote modify --local actarus user $DVC_ACTARUS_USERNAME
          dvc remote modify --local actarus password $DVC_ACTARUS_PASSWORD
      - name: dvc-pull-and-push
        run: |
          dvc pull -r gdrive
          dvc push -r ironspeed
          dvc push -r actarus