name: smells-short
on: [pull_request]
jobs:
  smells-short:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -lieo pipefail {0}
        working-directory: /usr/src/bohr
    container: giganticode/bohr-cml-base:latest
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      DVC_IRONSPEED_PASSWORD: ${{ secrets.DVC_IRONSPEED_PASSWORD }}
      PYTHONPATH: /usr/src/bohr/
    steps:
      - name: setup-python
        run: |
          pyenv global 3.8.0
          eval "$(pyenv init -)"
          echo "$(python --version)"
          echo "Python is $(pyenv which python)"
      - name: update-base-ref
        run: |
          git checkout $GITHUB_BASE_REF
          git pull
      - name: checkout-pull-request
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          git fetch origin pull/$PR_NUMBER/head:new-branch
          git checkout new-branch
          python -m pip install -r requirements.txt
      - name: install-dvc
        run: |
          pip install "dvc[ssh]==$(cat DVC_VERSION)"
          dvc --version
          dvc remote modify --local ironspeed user hbabii
          dvc remote modify --local ironspeed password $DVC_IRONSPEED_PASSWORD
      - name: repro
        run: |
          dvc pull -r ironspeed downloaded-data/smells-madeyski.csv
          dvc repro smells_10_label_dataset smells_10_train_label_model
      - name: report-metrics
        run: |
          git fetch --prune
          dvc metrics diff master
